id: A2CBCFC99
base_file: fE544.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-31 06:58:41.532737
  last_modified_at: 2022-05-31 06:58:41.532740
