id: A2CBCFC99
base_file: fCD4A.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 06:58:41.527467
  last_modified_at: 2022-05-31 06:58:41.527471
