id: A2CBCFC99
base_file: f0F3D.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-31 06:58:41.489833
  last_modified_at: 2022-05-31 06:58:41.489862
