id: A2CBCFC99
base_file: f1391.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-31 06:58:41.499754
  last_modified_at: 2022-05-31 06:58:41.499763
